{
 "title": "lb-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Traffic Distribution Per Backend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (backend_id) (rate(lb_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Average System Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(lb_request_duration_seconds_sum[$__rate_interval])) / sum(rate(lb_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections Per Backend",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend_id) (lb_active_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Latency Per Backend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, backend_id) (rate(lb_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(lb_requests_total{status_code=~\"5.*\"}[$__rate_interval])) or vector(0))\r\n/\r\nsum(rate(lb_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(lb_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}